name: Ruby

on: push

jobs:
  test:
    name: "Tests (on Ruby ${{ matrix.ruby_version }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_version: [3.0, 3.1, 3.2, 3.3]

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - name: Set up Ruby ${{ matrix.ruby_version }}
      uses: ruby/setup-ruby@e34163cd15f4bb403dcd72d98e295997e6a55798 # v1.238.0
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake test
