name: Ruby

on: push

jobs:
  test:
    name: "Tests (on Ruby ${{ matrix.ruby_version }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_version: [3.0, 3.1, 3.2, 3.3]

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up Ruby ${{ matrix.ruby_version }}
      uses: ruby/setup-ruby@dffc446db9ba5a0c4446edb5bca1c5c473a806c5 # v1.235.0
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake test
